// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCE8Y_ou3CKBSRkbXj_qIkOBX2tHBiBAY',
    appId: '1:1050375667505:web:ada8849219c6d47d387a10',
    messagingSenderId: '1050375667505',
    projectId: 'msoko-seller',
    authDomain: 'msoko-seller.firebaseapp.com',
    storageBucket: 'msoko-seller.appspot.com',
    measurementId: 'G-J8FH55NC39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlaQ_2bifPPGaAv3W34veUOfCREfvO2IU',
    appId: '1:1050375667505:android:8296936e3ad63cc2387a10',
    messagingSenderId: '1050375667505',
    projectId: 'msoko-seller',
    storageBucket: 'msoko-seller.appspot.com',
  );
}
